config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :concerts
  resources :groups

  root 'groups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
  belongs_to :Group

  validates :participants, presence: true
  validates :duration, presence: true
  validates :concert_date, presence: true
  validates :Group_id, presence: true
  validates :participants, :numericality => { :greater_than_or_equal_to => 0 }
  validates :duration, :numericality => { :greater_than_or_equal_to => 0 }
  
  def get_group_name
    self.Group.name
  end

  def to_s
    concert_date
  end
  
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :concerts, dependent: :destroy

    enum membersgender: [:men, :woman, :band]
    
    validates :members, presence: true
    validates :membersgender, presence: true
    validates :name, presence: true
    validates :members, :numericality => { :greater_than => 0 }
    
    def to_s
        name
    end

    def concerts_count
        Concert.where(Group_id: id).count
    end

    def debut
        @concerts = Concert.where(Group_id: id)
        dates = @concerts.map { |concert| concert.concert_date }
        if dates.any?
            dates.min
        else
            "This band don't have concerts"
        end
    end

    def total_asistants_over_time
        @concerts = Concert.where(Group_id: id)
        asistants = @concerts.map { |concert| concert.participants }
        if asistants.any?
            asistants.sum
        else
            "This band don't have concerts"
        end
    end

    def concerts_this_month
        @concerts = Concert.where(Group_id: id)
        concerts_month = []
        @concerts.each do |concert|
            if concert.concert_date > Time.now.beginning_of_month && concert.concert_date < Time.now.end_of_month
                concerts_month.push(concert.concert_date)
            end
        end
        if concerts_month.any?
            concerts_month.count
        else
            "This band don't have concerts this month"
        end
    end

    def last_concert
        @concerts = Concert.where(Group_id: id)
        the_last_concert = @concerts.map { |concert| concert.concert_date }
        if the_last_concert.any?
            the_last_concert.max.strftime("%Y, %B, %A")
        else
            "This band don't have concerts"
        end
    end

    def max_participants_in_concert
        @concerts = Concert.where(Group_id: id)
        max_participants = @concerts.map { |concert| concert.participants }
        if max_participants.any?
            max_participants.max 
        else
            "This band don't have concerts"
        end
    end

    def max_concert_duration
        @concerts = Concert.where(Group_id: id)
        max_duration = @concerts.map { |concert| concert.duration }
        if max_duration.any?
            Time.at((max_duration.max)*60).utc.strftime("%H:%M:%S") #minutes to seconds, then to format HH:MM:SS
        else
            "This band don't have concerts"
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
    before_action :set_concert, only: [:show, :edit, :update, :destroy]

    def index
        @concerts = Concert.all
    end

    def show
    end

    def new
        @concert = Concert.new 
        @groups = Group.all
    end

    def edit
        @groups = Group.all
    end

    def update
        @concert.update(concert_params)
    end

    def create
        @concert = Concert.new(concert_params)
        @groups = Group.all
        respond_to do |format|
            if @concert.save
                format.html { redirect_to concerts_url, notice: 'Concert was successfully created.' }
            else
                format.html { render :new }
            end
        end
    end

    def destroy
        @concert.destroy
        respond_to do |format|
            format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
        @concert = Concert.find(params[:id])
    end

    def concert_params
        params.require(:concert).permit(:participants, :duration, :concert_date, :Group_id)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :set_group, only: [:show, :edit, :update, :destroy]

    def index
        @groups = Group.all
    end

    def show
    end

    def new
        @group = Group.new 
    end

    def edit
    end

    def update
        @group.update(group_params)
    end

    def create
        @group = Group.new(group_params)
        respond_to do |format|
            if @group.save
                format.html { redirect_to concerts_url, notice: 'Group was successfully created.' }
            else
                format.html { render :new }
            end
        end
    end

    def destroy
        @group.destroy
        respond_to do |format|
            format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
        @group = Group.find(params[:id])
    end

    def group_params
        params.require(:group).permit(:members, :membersgender, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/concerts/_form.html.erb
<%= form_with(model: concert) do |form| %>
    <% if concert.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:
        </h2>

        <ul>
            <% concert.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <div class="field">
        <%= form.label :participants %>
        <%= form.text_field :participants %>
    </div>

    <div class="field">
        <%= form.label :duration_in_minutes %>
        <%= form.number_field :duration %>
    </div>

    <div class="field">
        <%= form.label :concert_date %>
        <%= form.date_field :concert_date %>
    </div>

    <div class="field">
        <select name="concert[Group_id]">
            <% @groups.each do |group| %>
                <option value="<%= group.id %>"><%= group.name %></option>
            <% end %>
        </select>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<h1>Concerts</h1>

<table>
    <thead>
        <tr>
            <th>Participants</th>
            <th>Duration</th>
            <th>Concert date</th>
            <th>Group</th>
        </tr>
    </thead>

    <tbody>
        <% @concerts.each do |concert| %>
            <tr>
                <td><%= concert.participants %></td>
                <td><%= concert.duration %></td>
                <td><%= concert.concert_date %></td>
                <td><%= concert.get_group_name %></td>

                <br>
                
                <td><%= link_to 'Show', concert %></td>
                <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
                <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Concert', new_concert_path %>
<%= link_to 'See Groups', groups_path %>

app/views/concerts/new.html.erb
<h1>Create new concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<h1>Concert Show</h1>

<p>
    <strong>Participants:</strong>
    <%= @concert.participants %>
</p>

<p>
    <strong>Concert Duration:</strong>
    <%= @concert.duration %>
</p>

<p>
    <strong>Concert Date:</strong>
    <%= @concert.concert_date %>
</p>

<p>
    <strong>Group:</strong>
    <%= @concert.get_group_name %>
<p>

<%= link_to 'Edit', edit_concert_path(@concert) %>
<%= link_to 'Back', concerts_path %>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
    <% if group.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:
        </h2>

        <ul>
            <% group.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <div class="field">
        <%= form.label :members %>
        <%= form.number_field :members %>
    </div>

    <div class="field">
        <%= form.label :membersgender %>
        <%= form.select :membersgender, Group.membersgenders.keys %>
    </div>

    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Members</th>
            <th>Members Gender</th>
            <th>Concerts</th>
            <th>Debut</th>
            <th>Total Asistants Over Time</th>
        </tr>
    </thead>

    <tbody>
        <% @groups.each do |group| %>
            <tr>
                <td><%= group.name %></td>
                <td><%= group.members %></td>
                <td><%= group.membersgender %></td>
                <td><%= group.concerts_count %></td>
                <td><%= group.debut %></td>
                <td><%= group.total_asistants_over_time %></td>


                <br>

                <td><%= link_to 'Show', group %></td>
                <td><%= link_to 'Edit', edit_group_path(group) %></td>
                <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>
<%= link_to 'See concerts', concerts_path %>

app/views/groups/new.html.erb
<h1>Create new concert</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<h1>Group Show</h1>

<p>
    <strong>Name:</strong>
    <%= @group.name %>
</p>

<p>
    <strong>Members:</strong>
    <%= @group.members %>
</p>

<p>
    <strong>Members Gender:</strong>
    <%= @group.membersgender %>
</p>

<p>
    <strong>Concerts this month:</strong>
    <%= @group.concerts_this_month %>
</p>

<p>
    <strong>Last concert:</strong>
    <%= @group.last_concert %>
</p>

<p>
    <strong>Max number of participants in concert:</strong>
    <%= @group.max_participants_in_concert %>
</p>

<p>
    <strong>Max concert duration:</strong>
    <%= @group.max_concert_duration %>
</p>



<%= link_to 'Edit', edit_group_path(@group) %>
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventsProducer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>